name: Build and Deploy Dockerized Python app to Azure Web App - ai-ticket-classifier

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Python environment for testing
      - name: Set up Python version
        uses: actions/setup-python@v1
        with:
          python-version: '3.10'

      - name: Install dependencies and run tests
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          pytest  # Ensure tests pass before proceeding

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/ai-ticket-classifier .

      # Log in to DockerHub
      - name: Log in to DockerHub
        run: |
          echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin

      # Push Docker image to DockerHub
      - name: Push Docker image to DockerHub
        run: |
          docker push your-dockerhub-username/ai-ticket-classifier

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      # Deploy Docker image to Azure Web App
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ai-ticket-classifier'
          images: 'your-dockerhub-username/ai-ticket-classifier:latest'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CBEF09C986C6458EBAC6C608EEF13A06 }}
