# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and Deploy Dockerized Python app to Azure Web App - ai-ticket-classifier

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Set up Docker Buildx (for building multi-architecture images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # Log in to DockerHub
      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # Build the Docker image
      - name: Build Docker image
        run: |
          docker build -t your-dockerhub-username/ai-ticket-classifier .

      # Push Docker image to DockerHub
      - name: Push Docker image
        run: |
          docker push your-dockerhub-username/ai-ticket-classifier

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'ai-ticket-classifier'
          images: 'your-dockerhub-username/ai-ticket-classifier:latest'  # Reference your Docker image
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_CBEF09C986C6458EBAC6C608EEF13A06 }}
